name:               "200 Word RPG Challenge"
description:        ""


url:                ""
author:             "Technical Grimoire"
email:              ""
gravatar_hash:      ""
twitter:            ""
email:              ""
github:             ""
pinterest:          ""
linkedin:           ""
facebook:           ""

disqus_shortname:   ""

background:         ""

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate