# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 200 Word RPG Challenge
description: > # this means to ignore newlines until "baseurl:"
  Organized by David Schirduan at 
  Technical Grimoire • schirduans.com
baseurl: "" 


# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
